version: '3.8'

services:
    mymbahome:
        image: mymbahome:0.1
        restart: always
        container_name: mymbahome
        build:
            context: .
            dockerfile: ./mymbahome/Dockerfile
        volumes:
            - static:/app/static_files
            - media:/app/media
            - ./mymbahome:/app
        expose:
            - 8000
        depends_on: 
            - mysql
        command: gunicorn --bind 0.0.0.0:8000 mymbahome.wsgi
        networks:
            - feeder
            - default
        links:
            - mysql

    mysql:
        image: mysql:5.7.22
        restart: always
        container_name: mysql
        environment: # environment variables to conect in django settings
            MYSQL_DATABASE: mymbahomedb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes: # data stored by mysql being mapping to host dir
            - .mysqldata:/var/lib/mysql
        ports: 
            - 3306:3306
        networks:
            - default

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        build: ./nginx
        ports: 
            - 80:80
        links: 
            - mymbahome
        depends_on: 
            - mymbahome
        volumes: 
            - static:/app/static_files
            - media:/app/media
        networks:
            - default

volumes:
    media:
    static:

# default network: ensures connection between home compose
# feeder network: ensures connection with mymbahome application
networks:
    default:
        name: home
        driver: bridge
    feeder:
        external: true
        name: feeder

# runs on docker-compose up -d