version: '3.8'

services:
    mymbahome:
        image: mymbahome:0.1
        restart: always
        container_name: mymbahome
        env_file: 
            - ./environment/dev.mymbahome.env
        build:
            context: .
            dockerfile: ./mymbahome/Dockerfile
        volumes:
            - static:/app/static_files
            - media:/app/media
            - ./mymbahome:/app
        depends_on: 
            - mysql
        command: gunicorn --bind 0.0.0.0:8000 mymbahome.wsgi
        networks:
            - default
        links:
            - mysql

    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        env_file: 
            - ./environment/dev.mysql.env
        volumes: # data stored by mysql being mapping to host dir
            - .mysqldata:/var/lib/mysql
        networks:
            - default
        command: --default-authentication-plugin=mysql_native_password
        # command: --default-auth=mysql_native_password

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        build: ./nginx
        ports: 
            - 80:80
        links: 
            - mymbahome
        depends_on: 
            - mymbahome
        volumes: 
            - static:/app/static_files
            - media:/app/media
        networks:
            - default

volumes:
    media:
    static:

networks:
    default:
        name: home
        driver: bridge
