version: '3.8'

services:
    mymbahome:
        restart: always
        container_name: mymbahome
        build:
            context: .
            dockerfile: Dockerfile
        # expose: 8000
        ports:
            - 80:8000
        # volumes:
        #     - .:/mymbahome
        command: python manage.py runserver 0.0.0.0:8000